services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - levir-ai-network
    restart: unless-stopped

  levir-ai-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/levir-ai-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - uploads:/home/levir-ai/uploads
      - ./config.toml:/home/levir-ai/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - levir-ai-network
    restart: unless-stopped

  levir-ai-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3001/api
        - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
        - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
        - NEXT_PUBLIC_WS_URL=ws://localhost:3001
    image: itzcrazykns1337/levir-ai-frontend:main
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    depends_on:
      - levir-ai-backend
    ports:
      - 3000:3000
    networks:
      - levir-ai-network
    restart: unless-stopped

networks:
  levir-ai-network:

volumes:
  backend-dbstore:
  uploads:
