use_default_settings: true

general:
  instance_name: 'Levir AI Search'
  debug: false
  enable_metrics: true

server:
  secret_key: ${SEARXNG_SECRET}
  bind_address: "0.0.0.0:8080"
  public_url: ${BASE_URL}
  base_url: /
  limiter: true
  image_proxy: false
  http_protocol_version: "1.0"
  method: "GET"
  default_http_headers:
    X-Content-Type-Options : nosniff
    X-XSS-Protection : 1; mode=block
    X-Download-Options : noopen
    X-Robots-Tag : noindex, nofollow
    Referrer-Policy : no-referrer
    Access-Control-Allow-Origin: ${BACKEND_URL}
    Access-Control-Allow-Methods: GET, OPTIONS
    Access-Control-Allow-Headers: Content-Type

search:
  safe_search: 0
  autocomplete: "google"
  formats:
    - html
    - json
  default_lang: "all"
  ban_time_on_fail: 60  # Increased for production
  max_ban_time_on_fail: 3600  # Increased for production

outgoing:
  request_timeout: 10
  max_request_timeout: 30
  pool_connections: 100
  pool_maxsize: 100
  enable_http2: true
  retries: 1
  proxies:
    http: ""
    https: ""
  using_tor_proxy: false
  extra_proxy_timeout: 10
  source_ips: []
  useragent_suffix: ""

engines:
  - name: google
    disabled: false
    
  - name: duckduckgo
    disabled: false
    
  - name: bing
    disabled: false
    
  - name: wikipedia
    disabled: false
    
  - name: wolframalpha
    disabled: false
  
  - name: youtube
    disabled: false
    
  - name: yahoo
    disabled: false
    
  - name: yahoo_news
    disabled: false
    
  - name: arxiv
    disabled: false
    
  - name: google scholar
    disabled: false
    
  - name: pubmed
    disabled: false
    
  - name: reddit
    disabled: false
    
  - name: bing images
    disabled: false
    
  - name: google images
    disabled: false 