services:
  - type: worker
    name: levir-ai-keepalive
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SEARXNG_URL
        value: https://levir-ai-searxng.onrender.com/healthz
      - key: BACKEND_URL  
        value: https://levir-ai-backend.onrender.com/api