use_default_settings: true

general:
  instance_name: 'Levir AI Search'

server:
  secret_key: 'a2fb23f1b02e6ee83875b09826990de0f6bd908b6638e8c10277d415f6ab852b'  # Is overwritten by ${SEARXNG_SECRET}

search:
  formats:
    - html
    - json

outgoing:
  request_timeout: 10
  max_request_timeout: 30

engines:
  - name: google
    disabled: false
    
  - name: duckduckgo
    disabled: false
    
  - name: bing
    disabled: false
    
  - name: wikipedia
    disabled: false
    
  - name: soundcloud
    disabled: true
    
  - name: wikidata
    disabled: true
    
  - name: wolframalpha
    disabled: true
  
  - name: youtube
    disabled: true
    
  - name: yahoo
    disabled: true
    
  - name: yahoo_news
    disabled: true
